# Generated by Django 3.2.8 on 2021-11-13 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customerId', models.IntegerField(default=-1)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('message', models.CharField(max_length=200)),
                ('vehicle', models.CharField(max_length=10)),
                ('sourName', models.CharField(max_length=500)),
                ('Scordlog', models.DecimalField(decimal_places=5, max_digits=5)),
                ('Scordlat', models.DecimalField(decimal_places=5, max_digits=5)),
                ('destName', models.CharField(max_length=500)),
                ('Dcordlog', models.DecimalField(decimal_places=5, max_digits=5)),
                ('Dcordlat', models.DecimalField(decimal_places=5, max_digits=5)),
                ('Rdate', models.DateField()),
                ('Rtime', models.TimeField()),
                ('step1', models.BooleanField(default=False)),
                ('step2', models.BooleanField(default=False)),
                ('step3', models.BooleanField(default=False)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
