# Generated by Django 3.2.8 on 2021-11-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_ride_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='Dcordlat',
            field=models.DecimalField(decimal_places=6, max_digits=13),
        ),
        migrations.AlterField(
            model_name='ride',
            name='Dcordlog',
            field=models.DecimalField(decimal_places=6, max_digits=13),
        ),
        migrations.AlterField(
            model_name='ride',
            name='Scordlat',
            field=models.DecimalField(decimal_places=6, max_digits=13),
        ),
        migrations.AlterField(
            model_name='ride',
            name='Scordlog',
            field=models.DecimalField(decimal_places=6, max_digits=13),
        ),
    ]
