# Generated by Django 3.2.8 on 2021-11-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20211113_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='vehicle',
            field=models.CharField(max_length=20),
        ),
    ]
