# Generated by Django 3.2.8 on 2021-11-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_ride_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='mylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customers', models.TextField(blank=True)),
            ],
        ),
    ]
