# Generated by Django 3.2.8 on 2021-11-14 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_mylist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='mylist',
        ),
    ]
