# Generated by Django 3.2.8 on 2021-11-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_delete_mylist'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='applied',
            field=models.TextField(null=True),
        ),
    ]
